name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm install

    - name: Create .env file
      run: |
        echo "REACT_APP_API_KEY=${{ secrets.REACT_APP_API_KEY }}" >> .env
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env

    - name: Build project
      run: npm run build
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Server
      run: npm run deploy
      env:
        REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
